### ISSUE TITLE
Ammo is not saved

### ISSUE THREAD

**Issue by oniatus** [MovingBlocks/DestinationSol#267] opened 2018-04-02 17:00 UTC
When a game is loaded the player will always start with full ammo.
Steps to reproduce:
1. Start a new game with "Loaded Imperial Large" starting ship
2. Fire some rounds with left and right gun
3. (optional): Respawn: The player keeps the ammo
4. Exit to menu then continue the game, the player has full ammo again
Money on the other hand is saved.

**Comment by Steampunkery** [comment] 2018-04-02 17:01
I can fix that. I'll get right on it.

**Comment by Steampunkery** [comment] 2018-06-14 02:52
I stopped working on this because gestalt integration will serialize the object, thus saving the ammo. I can make a temporary fix though.

**Comment by Avalancs** [comment] 2019-09-26 23:10
Tested on newest commit of develop branch, it has been fixed by https://github.com/MovingBlocks/DestinationSol/pull/318 so this issue can be closed.

**Comment by SimonC4** [comment] 2020-02-20 08:12
Closing this issue as it is confirmed as fixed in version 2.0.0.

**Closed by SimonC4** 2020-02-20 08:12 UTC
Labels: bug
