### ISSUE TITLE
Unexpected key config can cause weird effects like secondary gun auto-fire on ANY key

### ISSUE THREAD

**Issue by prestidigitator** [MovingBlocks/DestinationSol#34] opened 2015-06-14 04:21 UTC
To reproduce:

1. Change ships to a Wasp (or any other ship which can equip two weapons).
2. Equip two weapons.
3. Leave all menus and start flying.

Expected: Secondary weapon fires when secondary fire key is pressed, or worst case only when an enemy is in range and in the firing arc of the weapon (e.g. when a blaster in the primary slot would normally auto-aim).  Auto-firing the secondary weapon when there's a secondary trigger key in the controls should also only be enabled/disabled as an option, not forced behavior.

Actual: Depression and holding of any key (forward, left, right, etc.) causes the secondary weapon to fire continuously, as if the fire button were held down.

Observation: Weapons also seem to auto-equip in these ships when navigated to in the inventory screen, as if the fire button were held down.  May be a separate issue, but seems to occur in the same circumstances (ship with more than one weapon slot).

Impact: This issue makes more advanced ships pretty useless and difficult to utilize.  Only the blaster can be equipped as the secondary weapon; any other weapon will run out of ammunition in short order, and equipping a secondary weapon only when it should be fired is cumbersome and error prone.

EDIT: Oh.  Observed in commit 7e0f8243564cb2aebccfaa961cfd2bf957216030 on Git master branch, in KDE/Plasma5 on Arch Linux

**Comment by Cervator** [comment] 2015-06-14 18:58
Interesting bug! Although I can't reproduce :-(

I tried from source with the latest master branch. Tried two different advanced ships and differing weapons. Worked as expected. I *did* see that exiting the game and reloading changed which weapons were equipped, which is just one small part of eventually redoing saving to, well, actually saving :D

What happens if you delete settings.ini and start the game fresh? It should auto-generate a new one.

If still a problem try to edit the shoot keys in settings.ini to something out of the way, like `y` and `u`. Start the game. Does it still happen?

If not then I wonder if for some reason when the game launches on your OS and any key is depressed it also ends up counting as the one weapon key. You could probably add a little logging somewhere reporting on what keys are pressed and confirm it that way

**Comment by prestidigitator** [comment] 2015-06-15 03:36
Huh!  Actually, I had already changed my key mapping in main/settings.ini.  It turns out this was the problem.  I used a lower-case 'x' instead of an upper-case 'X' for keyShoot2.  Well, chalk this one up to user error.  Sorry about that.

**Comment by Cervator** [comment] 2015-06-15 03:58
Good to know, but that is still totally a bug we need to guard against (limit the impact of unexpected key settings) - so re-opening for fixing sometime later :-)

Will edit the title a little

**Comment by SimonC4** [comment] 2015-07-23 10:27
The configurable keyboard inputs in #49 should be sufficient to prevent this happening for most users. Could still happen if someone edits settings.ini but I don't know if we need to handle that situation.

**Comment by Cervator** [comment] 2015-07-26 05:29
Merged and agreed - adding to v1.3.0 as resolved :-)

**Closed by Cervator** 2015-07-26 05:29 UTC
Labels: bug
