### ISSUE TITLE
Crash while resizing window

### ISSUE THREAD

**Issue by gusbitencourt** [MovingBlocks/DestinationSol#105] opened 2016-08-01 17:57 UTC
http://pastebin.com/9FajR4du

**Comment by Cervator** [comment] 2016-08-01 18:44
Hi @GBitencourt and thanks for the report!

What system are you running the game on and where did you get the game from? Latest version on Steam? Is there anything unusual on your system that might impact window sizing? Like some sort of window position/size saving utility program, or anything of the kind?

The log statement is very useful and I see where the crash happen, I think we can avoid it at the very least by just canceling the resize or something like that, but am curious what caused that condition to occur in the first place.

**Comment by GBitencourt** [comment] 2016-08-01 22:56
I'm using windows 10. Downloaded the game on Steam. No, nothing.

Cancel the resizing would fix. You also could put prompt window to choose
the video configuration in the first launch...

I launched the game and started the tutorial, so it started in 800x600
windowed, so instead in change the resolution, I first maximized the
window, I didnt like it because it stretched the graphics, so I put it back
to normal and tried to resize it to keep the ratio and touch the screen
borders, than it crashed. I later launched, changed the screen resolution
and avoided to modify the window size through the window border.

Thanks,
Gustavo

**Comment by Cervator** [comment] 2016-08-04 03:28
We've been able to reproduce this issue now. Thanks again for reporting it @GBitencourt :-)

**Comment by GBitencourt** [comment] 2016-08-05 13:18
No problem! Good luck and thanks to keep me in touch!

On Thu, Aug 4, 2016 at 12:28 AM, Rasmus Praestholm <notifications@github.com

**Comment by crazywolf132** [comment] 2016-09-16 08:26
Anyone still got the paste? I fixed this issue for our version... but i don't remember what we changed.

**Comment by Cervator** [comment] 2017-01-01 07:55
Just got a new report of what is *probably* the same issue, and I think we can probably still figure out reproducing it. New pastebin also expires but here it is copy pasted in (probably another of the weird crash errors instead of just picking a safe number and logging a warning):

```
USER-GIVEN INFO:
Tried to change the size of the window using the cursor. I was able to grab the corner, but then the mouse was captured again and it brought the window down to 0 size and crashed.
 
ERROR STACK TRACE:
com.badlogic.gdx.utils.GdxRuntimeException: java.lang.AssertionError: normalizing NaN angle
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)
Caused by: java.lang.AssertionError: normalizing NaN angle
    at org.destinationsol.common.SolMath.norm(SolMath.java:80)
    at org.destinationsol.common.SolMath.angleDiff(SolMath.java:406)
    at org.destinationsol.game.input.Mover.needsToTurn(Mover.java:138)
    at org.destinationsol.game.screens.ShipMixedControl.update(ShipMixedControl.java:75)
    at org.destinationsol.game.screens.MainScreen.updateCustom(MainScreen.java:203)
    at org.destinationsol.ui.SolInputManager.update(SolInputManager.java:220)
    at org.destinationsol.SolApplication.update(SolApplication.java:132)
    at org.destinationsol.SolApplication.safeUpdate(SolApplication.java:111)
    at org.destinationsol.SolApplication.render(SolApplication.java:91)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
```

**Comment by Cervator** [comment] 2018-12-24 05:16
Closing this from age / high likelihood now invalid. Somewhat keeping track from newer issue #393

On win10 using the windows key to escape the window from in-game without pause I can resize without a crash at least, so that's something seemingly fixed :-)

Anybody still experiencing issues please open a new issue or add details to #393

**Closed by Cervator** 2018-12-24 05:16 UTC
Labels: bug
