### ISSUE TITLE
Add (and apply?) a consistent code style template

### ISSUE THREAD

**Issue by rzats** [MovingBlocks/DestinationSol#115] opened 2016-09-15 13:10 UTC
Currently most of the game's older code uses a mostly consistent but unconventional codestyle (2-space indentation,  one-line if blocks and several other subtle issues), while the newer (or recently modified) classes tend to use IDEA's default style template. It would be nice to switch the entire project to a consistent codestyle, preferably Terasology's existing template.
## Checklist
- [x] Add Terasology's code style file to the project.
- [x] Apply it as an IDE default via gradle.
- [x] Push a commit applying the code style to the entire project. Ideally all current pending contributions will be pushed before this so that they don't run into an overcomplicated git merge.

**Comment by Cervator** [comment] 2016-09-15 16:28
Yep, loads of this stuff to do, but would indeed be nice to do it after the big v2.0.0. Which could be very close! Just that silly little date format issue with Gestalt vs. Android's Java left (that we know of)

**Comment by rzats** [comment] 2016-09-16 13:16
@Cervator: sounds fairly reasonable :)
Is the date issue https://github.com/MovingBlocks/DestinationSol/pull/92#issuecomment-238939006? That sounds like it might require a fix/downgrade in gestalt rather than DS.

**Comment by Cervator** [comment] 2016-09-16 23:44
Yep, that's it. Potentially downgrading Gestalt's target Java version could work, but the problem is with Android's inconsistent adherence to Java 6-8 versioning (seemingly cherry picking different pieces from different versions). I googled and found an assortment of workarounds like handling date formats based on an OS check. That isn't necessarily pretty, but if there isn't too much of it (no idea if we'll hit more like it after the date format is fixed) it might be valuable to have the handling in Gestalt for Android compatibility while keeping it Java 8.

**Comment by Cervator** [comment] 2017-05-07 23:39
Closing as complete via #129 - I'm sure we can do more reformatting but this gets the one big giant bulk reformatting out of the way.

**Closed by Cervator** 2017-05-07 23:39 UTC
Labels: enhancement
