### ISSUE TITLE
form bearkilla

### ISSUE THREAD

**Issue by bearkilla** [MovingBlocks/DestinationSol#675] opened 2023-03-05 04:14 UTC
### How to reproduce

* Step 1
* Step 2
* Step 3

**Comment by BenjaminAmos** [comment] 2023-03-05 09:57
Crashing on start-up doesn't sound good! Unfortunately, I'm unlikely to be able to help here if I can't reproduce the crash. I'll need some more information in order to do that.

As a minimum, could you please provide the following information to help track-down the issue:
 - Operating System (Windows, macOS, Linux or Android)
 - Java Version (e.g. 8, 11, 17, 19)
 - Game Version (e.g. `2.0.0`, `develop` or a specific commit)
 
 It would also really help if you could attach a crash log too. If it exists, then it can usually be found in the same folder as the game's files. The log should have a name starting with `crash` or in severe cases `hs_err_pid`. You should be able to attach the file by dragging it into the reply text box. Otherwise, just paste the contents in.

**Comment by BenjaminAmos** [comment] 2023-03-19 11:42
@bearkilla Without further information, I am unable to fix the crash. Since you haven't responded with any further information in 2 weeks, I'm going to have to close this issue. Feel free to ask for it to be re-opened if you can provide some more detail.

**Closed by BenjaminAmos** 2023-03-19 11:42 UTC
