### ISSUE TITLE
Investigate create player flow

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/DestinationSol#326] opened 2018-10-07 01:22 UTC
PR #319 was a bit of a band-aid fix for some unexpected behavior around death, respawning, resuming a game, etc. @Adrijaned made a good comment to summarize:

> In one of oniatus' refactors of create player workflow, which accepts the new ship for player to create with items and such, or null if it is o be the same as previous, which is used on startup/respawn. However, when called with null, it loads the previous ship from savefile (y'know, startup), but for respawn, this means you respawn with ship you last used before saving.

With the auto-save from #319 in place so long as it triggers once then that avoids the issue. #325 Helped that general area a bit more as well. When we sort out #316 this round of weird inventory/death/respawn/restart issues may all be covered. However, none of those explicitly address that note - we should investigate and see if we could clear up that part of the code to harden against possible remaining bugs.

Most likely way to provoke: go through the steps in less than 30 seconds or simply make the auto-save period longer.

* Start a new game in some ship
* Exit and start another new game in some *other* ship
* Die before the auto-save triggers
* Respawn in the _first_ ship, not the second

**Comment by Adrijaned** [comment] 2018-10-07 08:41
First save is immediatelly after loading new world, then every 60 seconds. What might be more of an edge case, is when somebody dies within 60 seconds of purchasing new ship somewhere.

**Comment by Avalancs** [comment] 2019-09-27 00:51
On 5e08b6a5227285c9b8bbe59430caa4109623dd27 I was not able to reproduce either case, even though I cannot find which commit might have fixed the issue. To make testing quicker use the 'die' console command, which I added in https://github.com/MovingBlocks/DestinationSol/pull/431

**Comment by Adrijaned** [comment] 2019-09-30 21:08
Looks like I'm not capable of reproducing either either, closing

**Closed by Adrijaned** 2019-09-30 21:08 UTC
