### ISSUE TITLE
`W: An illegal reflective access operation has occurred` when creating a module.

### ISSUE THREAD

**Issue by jozefcifre** [MovingBlocks/DestinationSol#697] opened 2023-11-19 04:08 UTC
### What you were trying to do

I was trying to create a module like the wiki indicates: `./groovyw module create <moduleName>`.

$ `./groovyw module create test`

### What actually happened

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.ivy.util.url.IvyAuthenticator (file:/home/jvucq/.gradle/wrapper/dists/gradle-7.6-all/9f832ih6bniajn45pbmqhk2cw/gradle-7.6/lib/plugins/ivy-2.3.0.jar) to field java.net.Authenticator.theAuthenticator
WARNING: Please consider reporting this to the maintainers of org.apache.ivy.util.url.IvyAuthenticator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

### Game version

2.1.0 (develop)

### Log details

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.ivy.util.url.IvyAuthenticator (file:/home/jvucq/.gradle/wrapper/dists/gradle-7.6-all/9f832ih6bniajn45pbmqhk2cw/gradle-7.6/lib/plugins/ivy-2.3.0.jar) to field java.net.Authenticator.theAuthenticator
WARNING: Please consider reporting this to the maintainers of org.apache.ivy.util.url.IvyAuthenticator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
We're doing a create
User wants to create a module named: test
Creating target directory
Creating .gitignore
In copyInTemplateFiles for module test - copying in a build.gradle then next checking for module.json
WARNING: the module test did not have a module.json! One was created, please review and submit to GitHub
Added the remote 'origin' for module 'test' - but the URL https://github.com/DestinationSol/test.git failed a test lookup. Typo? Not created yet?
Created module named test

### Operating System

Linux

### Additional Info

Distro: NixOS

**Comment by BenjaminAmos** [comment] 2023-11-19 11:26
> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.ivy.util.url.IvyAuthenticator (file:/home/jvucq/.gradle/wrapper/dists/gradle-7.6-all/9f832ih6bniajn45pbmqhk2cw/gradle-7.6/lib/plugins/ivy-2.3.0.jar) to field java.net.Authenticator.theAuthenticator
WARNING: Please consider reporting this to the maintainers of org.apache.ivy.util.url.IvyAuthenticator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

This is a legitimate warning but it is harmless. It's complaining about one of the libraries provided by Gradle (the `groovyw` wrapper uses the Gradle runtime underneath). Java 9 changed things to do with reflection and even with Java 11 some libraries are still not compilant with the more strict requirements,

To cover the other warnings here:

> WARNING: the module test did not have a module.json! One was created, please review and submit to GitHub

This is an expected warning for a completely new module. It should create a new `module.json` for you from a template automatically.

> Added the remote 'origin' for module 'test' - but the URL https://github.com/DestinationSol/test.git failed a test lookup. Typo? Not created yet?

Most of our game modules live under the DestinationSol organisation on GitHub (https://github.com/DestinationSol/). If you want to use your own user repository then you'll need to create that repository on GitHub first and then change the origin with `git remote set-url origin https://github.com/<User>/<Module>.git` (run this in the module directory). I can arrange to have modules to be moved into the DestinationSol organisation quite easily, so just ask if you've got a module you'd like to see there.

Since this is not a bug, I'm going to close the issue. The module you tried to create was created successfully, as far as I can tell.

**Closed as completed by BenjaminAmos** 2023-11-19 11:26 UTC
Labels: bug

**Comment by jozefcifre** [comment] 2023-11-19 22:02
Understood. Thank you!
