### ISSUE TITLE
Crash on startup - fedora 26, nvidia

### ISSUE THREAD

**Issue by XakV** [MovingBlocks/DestinationSol#179] opened 2017-10-28 00:47 UTC
https://pastebin.com/j8z56FDN

### What you were trying to do

Launch game!

### What actually happened

Crash Reporter Worked!

### How to reproduce

* Step 1 Install Fedora 26, KDE, with NVidia proprietary drivers
* Step 2 Install Steam from Negativo17 repo
* Step 3 Use Native runtime
* Step 4 Launch Game
* Step 5 Report Issue ( having fun here, hope the pastebin was helpful )

### Computer details

I5 second or third gen, nvidia 710 or something.

**Comment by Cervator** [comment] 2017-10-28 02:06
Hi there! Thanks for the report, interesting log :-)

`Caused by: java.lang.RuntimeException: org.lwjgl.LWJGLException: No modes available`

Huh! That sounds like some sort of 3d wizardry. Wonder if our wizards will have any clues. Pinging @vampcat

**Comment by vampcat** [comment] 2017-10-28 08:06
I believe fedora 26 uses wayland, which is not supported by libdgx 2 (which is what we use).

**Comment by AffableZonkey** [comment] 2017-10-28 18:02
Hi - I wasn't using wayland. This was an X session in KDE Plasma 5. I can dig up journal stuff or provide more info if needed.

**Comment by AffableZonkey** [comment] 2017-10-28 23:04
Here's a selection of my glxinfo;

name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: NVIDIA Corporation
server glx version string: 1.4
server glx extensions:
client glx vendor string: NVIDIA Corporation
client glx version string: 1.4
client glx extensions:
GLX version: 1.4
GLX extensions:
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GT 710/PCIe/SSE2
OpenGL core profile version string: 4.5.0 NVIDIA 384.90
OpenGL core profile shading language version string: 4.50 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:

OpenGL version string: 4.5.0 NVIDIA 384.90
OpenGL shading language version string: 4.50 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 384.90
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

**Comment by Cervator** [comment] 2018-12-24 05:03
I'm going to close this now from age and from it _possibly_ being made obsolete by changes over the last year, especially with me just merging #360  which brings us to the latest LibGDX including using LWJGL 3 on the back-end.

@XakV if you happen to still be out there with the same system it could be cool to see if the game works now :-) Although you may have to try running the last develop branch from source rather than rely on a download, if able.

**Closed by Cervator** 2018-12-24 05:03 UTC
